% SPDX-FileCopyrightText: 2026 Stu Kozola
% SPDX-License-Identifier: Apache-2.0

function plan = buildfile
%BUILDFILE Build tasks for matlab-yfinance.

import matlab.buildtool.Task
import matlab.buildtool.tasks.CodeIssuesTask
import matlab.buildtool.tasks.TestTask

plan = buildplan(localfunctions);

plan("test") = TestTask("tests");
plan("check") = CodeIssuesTask(["+yfinance", "tests", "tests_live"]);
plan("docs") = Task( ...
    Description="Generate markdown API documentation.", ...
    Actions=@generateDocs);
plan("package") = Task( ...
    Description="Package matlab-yfinance as a MATLAB toolbox.", ...
    Dependencies=["test", "check", "docs"], ...
    Actions=@packageToolbox);
plan("packageOnly") = Task( ...
    Description="Package the toolbox without rerunning validation.", ...
    Dependencies="docs", ...
    Actions=@packageToolbox);
plan("liveTest") = Task( ...
    Description="Run opt-in live Yahoo Finance smoke tests.", ...
    Actions=@runLiveTests);

plan.DefaultTasks = "test";
end

function generateDocs(~)
projectRoot = fileparts(mfilename("fullpath"));
addpath(projectRoot);

docsFolder = fullfile(projectRoot, "docs");

if ~exist(docsFolder, "dir")
    mkdir(docsFolder);
end

publicFiles = dir(fullfile(projectRoot, "+yfinance", "*.m"));
names = sort(string({publicFiles.name}));
header = [
    "# API Reference"
    ""
    "_Generated by `buildtool docs` from public package files._"
    ""];
sections = cell(numel(names), 1);

for fileIndex = 1:numel(names)
    fileName = names(fileIndex);
    apiName = erase(fileName, ".m");
    qualifiedName = "yfinance." + apiName;
    sourceFile = fullfile(projectRoot, "+yfinance", fileName);
    sections{fileIndex} = [
        "## `" + qualifiedName + "`"
        ""
        firstHelpLine(sourceFile)
        ""
        propertyLines(qualifiedName)
        methodLines(qualifiedName)
        ""];
end

lines = [header; vertcat(sections{:})];
writelines(lines, fullfile(docsFolder, "API_REFERENCE.md"));
fprintf("Generated docs/API_REFERENCE.md\n");
end

function packageToolbox(~)
projectRoot = fileparts(mfilename("fullpath"));
addpath(projectRoot);
generateDocs([]);

distFolder = fullfile(projectRoot, "dist");

if ~exist(distFolder, "dir")
    mkdir(distFolder);
end

version = yfinance.version();
opts = matlab.addons.toolbox.ToolboxOptions(projectRoot, "matlab-yfinance");
opts.ToolboxName = "matlab-yfinance";
opts.ToolboxVersion = char(version);
opts.Summary = "Pure MATLAB implementation of core yfinance APIs.";
opts.Description = "MATLAB package for Yahoo Finance historical prices, metadata, " + ...
    "fundamentals, screeners, market/domain data, fund data, options, " + ...
    "search, and live quote polling.";
opts.AuthorName = "Stu Kozola";
opts.ToolboxFiles = packagedFiles(projectRoot);
opts.ToolboxMatlabPath = projectRoot;
opts.OutputFile = fullfile(distFolder, "matlab-yfinance-" + version + ".mltbx");

matlab.addons.toolbox.packageToolbox(opts);
fprintf("Packaged %s\n", opts.OutputFile);
end

function lines = methodLines(qualifiedName)
classInfo = meta.class.fromName(qualifiedName);

if isempty(classInfo)
    lines = strings(0, 1);
    return
end

methodInfo = classInfo.MethodList;
methodNames = strings(0, 1);
classParts = split(string(classInfo.Name), ".");
shortClassName = classParts(end);

for methodIndex = 1:numel(methodInfo)
    method = methodInfo(methodIndex);
    definingClassName = string(method.DefiningClass.Name);

    if string(method.Access) ~= "public" || method.Hidden || ...
            ~startsWith(definingClassName, "yfinance.") || ...
            string(method.Name) == shortClassName
        continue
    end

    methodNames(end + 1, 1) = string(method.Name); %#ok<AGROW>
end

methodNames = unique(methodNames, "stable");

if isempty(methodNames)
    lines = strings(0, 1);
    return
end

lines = ["Public methods:"; ""];

for methodName = methodNames(:).'
    lines(end + 1, 1) = "- `" + methodName + "`"; %#ok<AGROW>
end
end

function lines = propertyLines(qualifiedName)
classInfo = meta.class.fromName(qualifiedName);

if isempty(classInfo)
    lines = strings(0, 1);
    return
end

propertyInfo = classInfo.PropertyList;
propertyNames = strings(0, 1);

for propertyIndex = 1:numel(propertyInfo)
    property = propertyInfo(propertyIndex);
    definingClassName = string(property.DefiningClass.Name);

    if string(property.GetAccess) ~= "public" || property.Hidden || ~startsWith(definingClassName, "yfinance.")
        continue
    end

    propertyNames(end + 1, 1) = string(property.Name); %#ok<AGROW>
end

propertyNames = unique(propertyNames, "stable");

if isempty(propertyNames)
    lines = strings(0, 1);
    return
end

lines = ["Public properties:"; ""];

for propertyName = propertyNames(:).'
    lines(end + 1, 1) = "- `" + propertyName + "`"; %#ok<AGROW>
end

lines(end + 1, 1) = "";
end

function line = firstHelpLine(sourceFile)
contents = readlines(sourceFile, EmptyLineRule="skip");
line = "";

for lineIndex = 1:numel(contents)
    text = strtrim(contents(lineIndex));

    if startsWith(text, "% SPDX-")
        continue
    end

    if startsWith(text, "%")
        line = strtrim(extractAfter(text, 1));
        return
    end
end
end

function files = packagedFiles(projectRoot)
packageRoots = [
    "+yfinance"
    "docs"
    "examples"
    "tests"
    "tests_live"];
files = strings(0, 1);

for rootName = packageRoots(:).'
    files = [files; filesUnder(fullfile(projectRoot, rootName))]; %#ok<AGROW>
end

files = [
    files
    fullfile(projectRoot, "README.md")
    fullfile(projectRoot, "LICENSE")
    fullfile(projectRoot, "NOTICE")
    fullfile(projectRoot, "CONTRIBUTING.md")
    fullfile(projectRoot, "IMPLEMENTATION_PLAN.md")
    fullfile(projectRoot, "buildfile.m")];
files = files(isfile(files));
end

function runLiveTests(~)
projectRoot = fileparts(mfilename("fullpath"));
addpath(projectRoot);

if string(getenv("YFINANCE_LIVE_TESTS")) ~= "1"
    fprintf("Skipping live tests. Set YFINANCE_LIVE_TESTS=1 to run tests_live.\n");
    return
end

results = runtests(fullfile(projectRoot, "tests_live"));
disp(results);

if any([results.Failed]) || any([results.Incomplete])
    error("yfinance:LiveTestsFailed", "One or more live integration tests failed or were incomplete.");
end
end

function files = filesUnder(folder)
if ~exist(folder, "dir")
    files = strings(0, 1);
    return
end

listing = dir(fullfile(folder, "**", "*"));
listing = listing(~[listing.isdir]);
files = strings(numel(listing), 1);

for fileIndex = 1:numel(listing)
    files(fileIndex) = fullfile(listing(fileIndex).folder, listing(fileIndex).name);
end
end
