classdef TestOptions < matlab.unittest.TestCase
    %TESTOPTIONS Verify option expiration and chain handling.

    methods (TestClassSetup)
        function addProjectPaths(testCase)
            projectRoot = fileparts(fileparts(mfilename("fullpath")));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(projectRoot));
            testCase.applyFixture(matlab.unittest.fixtures.PathFixture(fullfile(projectRoot, "tests")));
        end
    end

    methods (Test)
        function responseConvertsToExpirations(testCase)
            expirations = yfinance.internal.optionsResponseToExpirations(optionFixture(), Symbol="AAPL");

            testCase.verifyClass(expirations, "datetime");
            testCase.verifyEqual(numel(expirations), 2);
            testCase.verifyEqual(string(expirations.TimeZone), "UTC");
        end

        function responseConvertsToOptionChain(testCase)
            chain = yfinance.internal.optionsResponseToOptionChain(optionFixture(), Symbol="AAPL");

            testCase.verifyEqual(chain.UnderlyingSymbol, "AAPL");
            testCase.verifyClass(chain.Calls, "table");
            testCase.verifyClass(chain.Puts, "table");
            testCase.verifyEqual(height(chain.Calls), 1);
            testCase.verifyEqual(height(chain.Puts), 1);
            testCase.verifyEqual(chain.Calls.ContractSymbol, "AAPL240119C00100000");
            testCase.verifyEqual(chain.Calls.Strike, 100);
            testCase.verifyTrue(chain.Calls.InTheMoney);
            testCase.verifyEqual(chain.Puts.ContractSymbol, "AAPL240119P00100000");
            testCase.verifyFalse(chain.Puts.InTheMoney);
        end

        function tickerOptionsUsesSession(testCase)
            session = StaticChartSession(emptyChartFixture(), OptionsResponse=optionFixture());
            ticker = yfinance.Ticker(" aapl ", Session=session);

            expirations = ticker.options();

            testCase.verifyEqual(session.LastOptionsSymbol, "AAPL");
            testCase.verifyEqual(numel(expirations), 2);
        end

        function tickerOptionChainUsesExpiration(testCase)
            session = StaticChartSession(emptyChartFixture(), OptionsResponse=optionFixture());
            ticker = yfinance.Ticker("AAPL", Session=session);
            expiration = datetime(2024, 1, 19, TimeZone="UTC");

            chain = ticker.optionChain(expiration);

            testCase.verifyEqual(session.LastOptionsRequest.Expiration, expiration);
            testCase.verifyEqual(chain.Calls.ContractSymbol, "AAPL240119C00100000");
        end

        function emptyOptionsResponseReportsNoData(testCase)
            response = struct("optionChain", struct("result", [], "error", []));

            testCase.verifyError( ...
                @() yfinance.internal.optionsResponseToOptionChain(response, Symbol="AAPL"), ...
                "yfinance:NoData");
        end
    end
end

function response = optionFixture()
expirationOne = 1705622400;
expirationTwo = 1706227200;
lastTradeDate = 1704205800;
callContract = struct( ...
    "contractSymbol", "AAPL240119C00100000", ...
    "strike", 100, ...
    "currency", "USD", ...
    "lastPrice", 25.5, ...
    "change", 1.2, ...
    "percentChange", 4.9, ...
    "volume", 100, ...
    "openInterest", 250, ...
    "bid", 25.0, ...
    "ask", 26.0, ...
    "contractSize", "REGULAR", ...
    "expiration", expirationOne, ...
    "lastTradeDate", lastTradeDate, ...
    "impliedVolatility", 0.25, ...
    "inTheMoney", true);
putContract = struct( ...
    "contractSymbol", "AAPL240119P00100000", ...
    "strike", 100, ...
    "currency", "USD", ...
    "lastPrice", 1.5, ...
    "change", -0.1, ...
    "percentChange", -6.25, ...
    "volume", 50, ...
    "openInterest", 125, ...
    "bid", 1.4, ...
    "ask", 1.6, ...
    "contractSize", "REGULAR", ...
    "expiration", expirationOne, ...
    "lastTradeDate", lastTradeDate, ...
    "impliedVolatility", 0.3, ...
    "inTheMoney", false);
optionSet = struct( ...
    "expirationDate", expirationOne, ...
    "hasMiniOptions", false, ...
    "calls", callContract, ...
    "puts", putContract);
quote = struct("symbol", "AAPL");
result = struct( ...
    "underlyingSymbol", "AAPL", ...
    "expirationDates", [expirationOne; expirationTwo], ...
    "strikes", [100; 105], ...
    "hasMiniOptions", false, ...
    "quote", quote, ...
    "options", optionSet);
response = struct("optionChain", struct("result", result, "error", []));
end

function response = emptyChartFixture()
response = struct("chart", struct("result", [], "error", []));
end
