function currentConfig = set_config(options)
%SET_CONFIG Update configuration using upstream-compatible option names.

arguments
    options.Proxy = []
    options.Retries = []
    options.Timeout = []
    options.UserAgent = []
    options.RetryDelay = []
    options.UseCredentials = []
    options.DebugLogging = []
    options.HideExceptions = []
    options.TimeZoneCacheLocation = []
end

currentConfig = yfinance.setConfig( ...
    Proxy=options.Proxy, ...
    Retries=options.Retries, ...
    Timeout=options.Timeout, ...
    UserAgent=options.UserAgent, ...
    RetryDelay=options.RetryDelay, ...
    UseCredentials=options.UseCredentials, ...
    DebugLogging=options.DebugLogging, ...
    HideExceptions=options.HideExceptions, ...
    TimeZoneCacheLocation=options.TimeZoneCacheLocation);
end
