function definition = calendarDefinition(calendarType)
%CALENDARDEFINITION Return Yahoo visualization metadata for a calendar.

calendarType = lower(strtrim(calendarType));

switch calendarType
    case "sp_earnings"
        definition = baseDefinition( ...
            calendarType, ...
            "intradaymarketcap", ...
            ["ticker", "companyshortname", "intradaymarketcap", "eventname", ...
            "startdatetime", "startdatetimetype", "epsestimate", "epsactual", ...
            "epssurprisepct"], ...
            ["MarketCap", "EPSEstimate", "ReportedEPS", "SurprisePercent"], ...
            ["EPSEstimate", "ReportedEPS", "SurprisePercent"], ...
            "EventStartDate");
    case "ipo_info"
        definition = baseDefinition( ...
            calendarType, ...
            "startdatetime", ...
            ["ticker", "companyshortname", "exchdisp", "startdatetime", ...
            "startdatetimetype", "proposedTickerSymbol", "proposedExchangeSymbol", ...
            "sharesOffered", "proposedSharePrice", "pricedDate", "dollarValueOfSharesOffered"], ...
            ["SharesOffered", "ProposedSharePrice", "DollarValueOfSharesOffered"], ...
            ["SharesOffered", "ProposedSharePrice", "DollarValueOfSharesOffered"], ...
            ["EventStartDate", "PricedDate"]);
    case "economic_event"
        definition = baseDefinition( ...
            calendarType, ...
            "startdatetime", ...
            ["eventname", "country", "startdatetime", "timeZoneShortName", ...
            "gmtOffsetMilliSeconds", "period", "consensus", "actual", "previous", "revised"], ...
            ["GmtOffsetMilliseconds", "Consensus", "Actual", "Previous", "Revised"], ...
            ["Consensus", "Actual", "Previous", "Revised"], ...
            "EventStartDate");
    case "splits"
        definition = baseDefinition( ...
            calendarType, ...
            "startdatetime", ...
            ["ticker", "companyshortname", "startdatetime", "startdatetimetype", ...
            "ratio", "optionable"], ...
            strings(0, 1), ...
            strings(0, 1), ...
            "EventStartDate");
    otherwise
        error("yfinance:InvalidCalendarType", "Unsupported calendar type '%s'.", calendarType);
end
end

function definition = baseDefinition(calendarType, sortField, includeFields, numericColumns, zeroAsMissingColumns, datetimeColumns)
definition = struct();
definition.CalendarType = calendarType;
definition.SortField = sortField;
definition.IncludeFields = includeFields(:).';
definition.NumericColumns = numericColumns(:).';
definition.ZeroAsMissingColumns = zeroAsMissingColumns(:).';
definition.DatetimeColumns = datetimeColumns(:).';
end
