% SPDX-FileCopyrightText: 2026 Stu Kozola
% SPDX-License-Identifier: Apache-2.0

function defaults = configDefaults()
%CONFIGDEFAULTS Return default matlab-yfinance configuration.

defaults = struct();
defaults.network = struct( ...
    "proxy", "", ...
    "retries", 2);
defaults.debug = struct( ...
    "logging", false, ...
    "hide_exceptions", true);
defaults.session = struct( ...
    "timeout", 30, ...
    "userAgent", yfinance.internal.defaultUserAgent(), ...
    "retryDelay", 0.5, ...
    "useCredentials", true);
defaults.timezoneCacheLocation = "";
end
