% SPDX-FileCopyrightText: 2026 Stu Kozola
% SPDX-License-Identifier: Apache-2.0

function modules = defaultInfoModules()
%DEFAULTINFOMODULES Return quoteSummary modules used by Ticker.info.

modules = [ ...
    "price", ...
    "summaryProfile", ...
    "summaryDetail", ...
    "defaultKeyStatistics", ...
    "financialData", ...
    "quoteType", ...
    "assetProfile"];
end
