% SPDX-FileCopyrightText: 2026 Stu Kozola
% SPDX-License-Identifier: Apache-2.0

function types = fundamentalsTimeSeriesTypes(statementType, frequency)
%FUNDAMENTALSTIMESERIESTYPES Return Yahoo fundamentals time-series types.

arguments
    statementType (1,1) string
    frequency (1,1) string = "trailing"
end

statementType = lower(strtrim(statementType));
frequency = lower(strtrim(frequency));

switch frequency
    case "trailing"
        prefix = "trailing";
    otherwise
        error("yfinance:InvalidFrequency", "Unsupported fundamentals time-series frequency: %s.", frequency);
end

switch statementType
    case "income"
        keys = incomeStatementKeys();
    case "cashflow"
        keys = cashFlowKeys();
    otherwise
        error("yfinance:InvalidStatement", "Unsupported fundamentals time-series statement: %s.", statementType);
end

types = prefix + keys;
end

function keys = incomeStatementKeys()
keys = [ ...
    "TaxEffectOfUnusualItems", ...
    "TaxRateForCalcs", ...
    "NormalizedEBITDA", ...
    "NormalizedDilutedEPS", ...
    "NormalizedBasicEPS", ...
    "TotalUnusualItems", ...
    "TotalUnusualItemsExcludingGoodwill", ...
    "NetIncomeFromContinuingOperationNetMinorityInterest", ...
    "ReconciledDepreciation", ...
    "ReconciledCostOfRevenue", ...
    "EBITDA", ...
    "EBIT", ...
    "NetInterestIncome", ...
    "InterestExpense", ...
    "InterestIncome", ...
    "ContinuingAndDiscontinuedDilutedEPS", ...
    "ContinuingAndDiscontinuedBasicEPS", ...
    "NormalizedIncome", ...
    "NetIncomeFromContinuingAndDiscontinuedOperation", ...
    "TotalExpenses", ...
    "ReportedNormalizedDilutedEPS", ...
    "ReportedNormalizedBasicEPS", ...
    "TotalOperatingIncomeAsReported", ...
    "DilutedAverageShares", ...
    "BasicAverageShares", ...
    "DilutedEPS", ...
    "BasicEPS", ...
    "DilutedNIAvailtoComStockholders", ...
    "NetIncomeCommonStockholders", ...
    "NetIncome", ...
    "MinorityInterests", ...
    "NetIncomeIncludingNoncontrollingInterests", ...
    "NetIncomeContinuousOperations", ...
    "TaxProvision", ...
    "PretaxIncome", ...
    "OtherIncomeExpense", ...
    "OperatingIncome", ...
    "OperatingExpense", ...
    "ResearchAndDevelopment", ...
    "SellingGeneralAndAdministration", ...
    "GrossProfit", ...
    "CostOfRevenue", ...
    "TotalRevenue", ...
    "OperatingRevenue"];
end

function keys = cashFlowKeys()
keys = [ ...
    "FreeCashFlow", ...
    "RepurchaseOfCapitalStock", ...
    "RepaymentOfDebt", ...
    "IssuanceOfDebt", ...
    "IssuanceOfCapitalStock", ...
    "CapitalExpenditure", ...
    "InterestPaidSupplementalData", ...
    "IncomeTaxPaidSupplementalData", ...
    "EndCashPosition", ...
    "BeginningCashPosition", ...
    "EffectOfExchangeRateChanges", ...
    "ChangesInCash", ...
    "FinancingCashFlow", ...
    "CashDividendsPaid", ...
    "CommonStockDividendPaid", ...
    "NetCommonStockIssuance", ...
    "CommonStockPayments", ...
    "CommonStockIssuance", ...
    "NetIssuancePaymentsOfDebt", ...
    "NetLongTermDebtIssuance", ...
    "LongTermDebtPayments", ...
    "LongTermDebtIssuance", ...
    "InvestingCashFlow", ...
    "NetInvestmentPurchaseAndSale", ...
    "SaleOfInvestment", ...
    "PurchaseOfInvestment", ...
    "NetBusinessPurchaseAndSale", ...
    "PurchaseOfBusiness", ...
    "NetPPEPurchaseAndSale", ...
    "SaleOfPPE", ...
    "PurchaseOfPPE", ...
    "CapitalExpenditureReported", ...
    "OperatingCashFlow", ...
    "CashFlowFromContinuingOperatingActivities", ...
    "ChangeInWorkingCapital", ...
    "ChangeInPayablesAndAccruedExpense", ...
    "ChangeInInventory", ...
    "ChangeInReceivables", ...
    "ChangesInAccountReceivables", ...
    "StockBasedCompensation", ...
    "DeferredTax", ...
    "DepreciationAmortizationDepletion", ...
    "DepreciationAndAmortization", ...
    "OperatingGainsLosses", ...
    "NetIncomeFromContinuingOperations"];
end
