function definitions = predefinedScreenerQueryDefinitions()
%PREDEFINEDSCREENERQUERYDEFINITIONS Return upstream predefined screener definitions.

definitions = struct();

definitions.aggressive_small_caps = definition( ...
    yfinance.EquityQuery("and", { ...
        yfinance.EquityQuery("is-in", {"exchange", "NMS", "NYQ"}), ...
        yfinance.EquityQuery("lt", {"epsgrowth.lasttwelvemonths", 15})}), ...
    "eodvolume", ...
    "DESC");
definitions.day_gainers = definition( ...
    yfinance.EquityQuery("and", { ...
        yfinance.EquityQuery("gt", {"percentchange", 3}), ...
        yfinance.EquityQuery("eq", {"region", "us"}), ...
        yfinance.EquityQuery("gte", {"intradaymarketcap", 2000000000}), ...
        yfinance.EquityQuery("gte", {"intradayprice", 5}), ...
        yfinance.EquityQuery("gt", {"dayvolume", 15000})}), ...
    "percentchange", ...
    "DESC");
definitions.day_losers = definition( ...
    yfinance.EquityQuery("and", { ...
        yfinance.EquityQuery("lt", {"percentchange", -2.5}), ...
        yfinance.EquityQuery("eq", {"region", "us"}), ...
        yfinance.EquityQuery("gte", {"intradaymarketcap", 2000000000}), ...
        yfinance.EquityQuery("gte", {"intradayprice", 5}), ...
        yfinance.EquityQuery("gt", {"dayvolume", 20000})}), ...
    "percentchange", ...
    "ASC");
definitions.growth_technology_stocks = definition( ...
    yfinance.EquityQuery("and", { ...
        yfinance.EquityQuery("gte", {"quarterlyrevenuegrowth.quarterly", 25}), ...
        yfinance.EquityQuery("gte", {"epsgrowth.lasttwelvemonths", 25}), ...
        yfinance.EquityQuery("eq", {"sector", "Technology"}), ...
        yfinance.EquityQuery("is-in", {"exchange", "NMS", "NYQ"})}), ...
    "eodvolume", ...
    "DESC");
definitions.most_actives = definition( ...
    yfinance.EquityQuery("and", { ...
        yfinance.EquityQuery("eq", {"region", "us"}), ...
        yfinance.EquityQuery("gte", {"intradaymarketcap", 2000000000}), ...
        yfinance.EquityQuery("gt", {"dayvolume", 5000000})}), ...
    "dayvolume", ...
    "DESC");
definitions.most_shorted_stocks = definition( ...
    yfinance.EquityQuery("and", { ...
        yfinance.EquityQuery("eq", {"region", "us"}), ...
        yfinance.EquityQuery("gt", {"intradayprice", 1}), ...
        yfinance.EquityQuery("gt", {"avgdailyvol3m", 200000})}), ...
    "short_percentage_of_shares_outstanding.value", ...
    "DESC", ...
    Count=25, ...
    Offset=0);
definitions.small_cap_gainers = definition( ...
    yfinance.EquityQuery("and", { ...
        yfinance.EquityQuery("lt", {"intradaymarketcap", 2000000000}), ...
        yfinance.EquityQuery("is-in", {"exchange", "NMS", "NYQ"})}), ...
    "eodvolume", ...
    "DESC");
definitions.undervalued_growth_stocks = definition( ...
    yfinance.EquityQuery("and", { ...
        yfinance.EquityQuery("btwn", {"peratio.lasttwelvemonths", 0, 20}), ...
        yfinance.EquityQuery("lt", {"pegratio_5y", 1}), ...
        yfinance.EquityQuery("gte", {"epsgrowth.lasttwelvemonths", 25}), ...
        yfinance.EquityQuery("is-in", {"exchange", "NMS", "NYQ"})}), ...
    "eodvolume", ...
    "DESC");
definitions.undervalued_large_caps = definition( ...
    yfinance.EquityQuery("and", { ...
        yfinance.EquityQuery("btwn", {"peratio.lasttwelvemonths", 0, 20}), ...
        yfinance.EquityQuery("lt", {"pegratio_5y", 1}), ...
        yfinance.EquityQuery("btwn", {"intradaymarketcap", 10000000000, 100000000000}), ...
        yfinance.EquityQuery("is-in", {"exchange", "NMS", "NYQ"})}), ...
    "eodvolume", ...
    "DESC");

definitions.conservative_foreign_funds = definition( ...
    yfinance.FundQuery("and", { ...
        yfinance.FundQuery("is-in", { ...
            "categoryname", ...
            "Foreign Large Value", ...
            "Foreign Large Blend", ...
            "Foreign Large Growth", ...
            "Foreign Small/Mid Growth", ...
            "Foreign Small/Mid Blend", ...
            "Foreign Small/Mid Value"}), ...
        yfinance.FundQuery("is-in", {"performanceratingoverall", 4, 5}), ...
        yfinance.FundQuery("lt", {"initialinvestment", 100001}), ...
        yfinance.FundQuery("lt", {"annualreturnnavy1categoryrank", 50}), ...
        yfinance.FundQuery("is-in", {"riskratingoverall", 1, 2, 3}), ...
        yfinance.FundQuery("eq", {"exchange", "NAS"})}), ...
    "fundnetassets", ...
    "DESC");
definitions.high_yield_bond = definition( ...
    yfinance.FundQuery("and", { ...
        yfinance.FundQuery("is-in", {"performanceratingoverall", 4, 5}), ...
        yfinance.FundQuery("lt", {"initialinvestment", 100001}), ...
        yfinance.FundQuery("lt", {"annualreturnnavy1categoryrank", 50}), ...
        yfinance.FundQuery("is-in", {"riskratingoverall", 1, 2, 3}), ...
        yfinance.FundQuery("eq", {"categoryname", "High Yield Bond"}), ...
        yfinance.FundQuery("eq", {"exchange", "NAS"})}), ...
    "fundnetassets", ...
    "DESC");
definitions.portfolio_anchors = definition( ...
    yfinance.FundQuery("and", { ...
        yfinance.FundQuery("eq", {"categoryname", "Large Blend"}), ...
        yfinance.FundQuery("is-in", {"performanceratingoverall", 4, 5}), ...
        yfinance.FundQuery("lt", {"initialinvestment", 100001}), ...
        yfinance.FundQuery("lt", {"annualreturnnavy1categoryrank", 50}), ...
        yfinance.FundQuery("eq", {"exchange", "NAS"})}), ...
    "fundnetassets", ...
    "DESC");
definitions.solid_large_growth_funds = definition( ...
    yfinance.FundQuery("and", { ...
        yfinance.FundQuery("eq", {"categoryname", "Large Growth"}), ...
        yfinance.FundQuery("is-in", {"performanceratingoverall", 4, 5}), ...
        yfinance.FundQuery("lt", {"initialinvestment", 100001}), ...
        yfinance.FundQuery("lt", {"annualreturnnavy1categoryrank", 50}), ...
        yfinance.FundQuery("eq", {"exchange", "NAS"})}), ...
    "fundnetassets", ...
    "DESC");
definitions.solid_midcap_growth_funds = definition( ...
    yfinance.FundQuery("and", { ...
        yfinance.FundQuery("eq", {"categoryname", "Mid-Cap Growth"}), ...
        yfinance.FundQuery("is-in", {"performanceratingoverall", 4, 5}), ...
        yfinance.FundQuery("lt", {"initialinvestment", 100001}), ...
        yfinance.FundQuery("lt", {"annualreturnnavy1categoryrank", 50}), ...
        yfinance.FundQuery("eq", {"exchange", "NAS"})}), ...
    "fundnetassets", ...
    "DESC");
definitions.top_mutual_funds = definition( ...
    yfinance.FundQuery("and", { ...
        yfinance.FundQuery("gt", {"intradayprice", 15}), ...
        yfinance.FundQuery("is-in", {"performanceratingoverall", 4, 5}), ...
        yfinance.FundQuery("gt", {"initialinvestment", 1000}), ...
        yfinance.FundQuery("eq", {"exchange", "NAS"})}), ...
    "percentchange", ...
    "DESC");

definitions.top_etfs_us = definition( ...
    yfinance.ETFQuery("and", { ...
        yfinance.ETFQuery("gt", {"intradayprice", 10}), ...
        yfinance.ETFQuery("is-in", {"performanceratingoverall", 4, 5}), ...
        yfinance.ETFQuery("eq", {"region", "us"})}), ...
    "percentchange", ...
    "DESC");
definitions.top_performing_etfs = definition( ...
    yfinance.ETFQuery("and", { ...
        yfinance.ETFQuery("eq", {"region", "us"}), ...
        yfinance.ETFQuery("is-in", {"performanceratingoverall", 4, 5}), ...
        yfinance.ETFQuery("gt", {"intradayprice", 10})}), ...
    "annualreportnetexpenseratio", ...
    "ASC");
definitions.technology_etfs = definition( ...
    yfinance.ETFQuery("and", { ...
        yfinance.ETFQuery("eq", {"region", "us"}), ...
        yfinance.ETFQuery("eq", {"categoryname", "Technology"})}), ...
    "annualreportnetexpenseratio", ...
    "ASC");
definitions.bond_etfs = definition( ...
    yfinance.ETFQuery("and", { ...
        yfinance.ETFQuery("eq", {"region", "us"}), ...
        yfinance.ETFQuery("is-in", { ...
            "categoryname", ...
            "Corporate Bond", ...
            "Emerging Markets Bond", ...
            "Emerging-Markets Local-Currency Bond", ...
            "High Yield Bond", ...
            "Intermediate-Term Bond", ...
            "Long-Term Bond", ...
            "Inflation-Protected Bond", ...
            "Multisector Bond", ...
            "Nontraditional Bond", ...
            "Short-Term Bond", ...
            "Ultrashort Bond", ...
            "World Bond"})}), ...
    "annualreportnetexpenseratio", ...
    "ASC");
end

function value = definition(query, sortField, sortType, options)
arguments
    query (1,1) yfinance.internal.ScreenerQuery
    sortField (1,1) string {mustBeNonzeroLengthText}
    sortType (1,1) string {mustBeNonzeroLengthText}
    options.Count (1,1) double = NaN
    options.Offset (1,1) double = NaN
end

sortType = upper(strtrim(sortType));

if ~ismember(sortType, ["ASC", "DESC"])
    error("yfinance:InvalidSortType", "Sort type must be ASC or DESC.");
end

value = struct();
value.Query = query;
value.QuoteType = query.QuoteType;
value.SortField = sortField;
value.SortType = sortType;
value.SortAscending = sortType == "ASC";
value.Count = options.Count;
value.Offset = options.Offset;
end
