function data = quoteSummaryResponseToValuation(response, options)
%QUOTESUMMARYRESPONSETOVALUATION Convert valuation quoteSummary fields to rows.

arguments
    response struct
    options.Symbol (1,1) string = ""
end

result = yfinance.internal.quoteSummaryResult(response, Symbol=options.Symbol);
[moduleNames, fieldNames] = valuationFields();
rowCapacity = numel(fieldNames);
metric = strings(rowCapacity, 1);
field = strings(rowCapacity, 1);
value = NaN(rowCapacity, 1);
formatted = strings(rowCapacity, 1);
module = strings(rowCapacity, 1);
seenFields = strings(0, 1);
rowCount = 0;

for fieldIndex = 1:rowCapacity
    moduleName = moduleNames(fieldIndex);
    fieldName = fieldNames(fieldIndex);

    if ismember(fieldName, seenFields) || ~isfield(result, moduleName) || isempty(result.(moduleName))
        continue
    end

    moduleData = result.(moduleName);

    if ~isstruct(moduleData) || ~isfield(moduleData, fieldName) || isempty(moduleData.(fieldName))
        continue
    end

    [rawValue, formattedValue, hasValue] = valuationValue(moduleData.(fieldName));

    if ~hasValue
        continue
    end

    rowCount = rowCount + 1;
    metric(rowCount) = yfinance.internal.pascalFieldName(fieldName);
    field(rowCount) = fieldName;
    value(rowCount) = rawValue;
    formatted(rowCount) = formattedValue;
    module(rowCount) = moduleName;
    seenFields(end + 1, 1) = fieldName; %#ok<AGROW>
end

data = table( ...
    metric(1:rowCount), ...
    field(1:rowCount), ...
    value(1:rowCount), ...
    formatted(1:rowCount), ...
    module(1:rowCount), ...
    VariableNames={'Metric', 'Field', 'Value', 'Formatted', 'Module'});
data.Properties.UserData = struct("Symbol", options.Symbol, "Module", "valuation");
end

function [moduleNames, fieldNames] = valuationFields()
moduleNames = [ ...
    "price"; ...
    "price"; ...
    "summaryDetail"; ...
    "summaryDetail"; ...
    "summaryDetail"; ...
    "summaryDetail"; ...
    "summaryDetail"; ...
    "summaryDetail"; ...
    "summaryDetail"; ...
    "defaultKeyStatistics"; ...
    "defaultKeyStatistics"; ...
    "defaultKeyStatistics"; ...
    "defaultKeyStatistics"; ...
    "defaultKeyStatistics"; ...
    "defaultKeyStatistics"; ...
    "defaultKeyStatistics"; ...
    "financialData"; ...
    "financialData"; ...
    "financialData"; ...
    "financialData"; ...
    "financialData"; ...
    "financialData"; ...
    "financialData"; ...
    "financialData"; ...
    "financialData"; ...
    "financialData"; ...
    "financialData"];
fieldNames = [ ...
    "marketCap"; ...
    "regularMarketPrice"; ...
    "beta"; ...
    "trailingPE"; ...
    "forwardPE"; ...
    "priceToSalesTrailing12Months"; ...
    "dividendRate"; ...
    "dividendYield"; ...
    "payoutRatio"; ...
    "enterpriseValue"; ...
    "pegRatio"; ...
    "priceToBook"; ...
    "enterpriseToRevenue"; ...
    "enterpriseToEbitda"; ...
    "bookValue"; ...
    "trailingEps"; ...
    "currentPrice"; ...
    "targetMeanPrice"; ...
    "recommendationMean"; ...
    "numberOfAnalystOpinions"; ...
    "profitMargins"; ...
    "grossMargins"; ...
    "ebitdaMargins"; ...
    "operatingMargins"; ...
    "revenuePerShare"; ...
    "totalCashPerShare"; ...
    "ebitda"];
end

function [rawValue, formattedValue, hasValue] = valuationValue(inputValue)
rawValue = NaN;
formattedValue = "";
hasValue = false;

if isstruct(inputValue)
    if isfield(inputValue, "fmt") && ~isempty(inputValue.fmt)
        formattedValue = string(inputValue.fmt);
    end

    inputValue = yfinance.internal.unwrapYahooValue(inputValue);
end

if isnumeric(inputValue) && isscalar(inputValue) && ~isnan(inputValue)
    rawValue = double(inputValue);
    hasValue = true;

    if formattedValue == ""
        formattedValue = string(inputValue);
    end
end
end
